spring:
  data:
    mongodb:
      uri: mongodb+srv://humaidjaffery:Billybobjoe2152%40@cyberpolis.bzc0s.mongodb.net/cyberpolis
      database: cyberpolis
  app:
    jwtSecret: testSecretKeymyverylongkyemyverylongkeymyvery
    jwtExpirationMs: 60480000

logging:
  level:
    org.springframework: DEBUG
