spring:
  datasource:
#    driverClassName: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/cyberpolis
    password: billybobjoe2152
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
  app:
    jwtSecret: testSecretKeymyverylongkyemyverylongkeymyvery
    jwtExpirationMs: 60480000

logging:
  level:
    org.springframework: DEBUG
